### ISSUE TITLE
labels.alertname is not working 

### ISSUE THREAD

**Issue by freeseacher** [alerta/prometheus-config#15]
according to https://github.com/prometheus/prometheus/issues/2818
 it is expected behaviour

**Comment by satterly** [comment]
It seems the `alertname` variable is only available as a groupLabel in a notification template, and you can't template webhooks. Go figure.

Any suggestions?

**Comment by freeseacher** [comment]
currently i moved from annotations in alert rules to alerta telegram template 
mine now is 
```
{% if customer %}Customer: `{{customer}}` {% endif %}

*[{{ status.capitalize() }}] {{ environment }} {{ severity.capitalize() }}*
{{ event | replace("_","\_") }} {{ resource.capitalize() }}

\`\`\`
{{ text }}
\`\`\`

{% if status == 'open' %}[Runbook](https://XXXX/display/NOCRUN/{{ event | replace("_","") }}){% endif %}
```

It works but that is not what i'm expected to see. 

Btw that issue not for solving but probably about fixing doc to bee less frustrating

**Comment by satterly** [comment]
That's very interesting. How is that template picked up? Can you paste an example Prometheus and Alertmanager config file so that I can understand how it all hangs together? Thanks.

**Comment by satterly** [comment]
I've updated the README (by deleting all references to runbook) and the example config (by adding a note) to reflect that `alertname` is not supported in annotation.

**Comment by satterly** [comment]
Your opinion on https://github.com/alerta/alerta/pull/732 would be appreciated. Thanks.

**Comment by freeseacher** [comment]
> That's very interesting. How is that template picked up? Can you paste an example Prometheus and Alertmanager config file so that I can understand how it all hangs together? Thanks.

alertmanager.yaml
```
global:
  http_config:
    proxy_url: 'http://proxy:3128'
  smtp_smarthost: mysmtp
  smtp_from: mymail
  smtp_require_tls: false
  smtp_hello: prom
  smtp_auth_username: yyy
  smtp_auth_password: xxx

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    # Apply inhibition if the alertname is the same.
    equal: ['alertname']

route:
  group_wait: 30s
  group_interval: 1m
  receiver: 'alerta'
  routes: 
    - receiver: 'alerta'
      continue: true
    - receiver: "infra-alert"
      match: 
        scope: infra
    - receiver: "system-alert"
      match: 
        scope: system

receivers:
  - name: "alerta"
    webhook_configs:
    - url: 'https://alerta.XXX/api/webhooks/prometheus?api-key=XXXX'
      send_resolved: true
  - name: "system-alert"
    email_configs:
      - to:  system-alert@XXX
        send_resolved: true 
  - name: "infra-alert"
    email_configs:
      - to:  infra-alert@XXX
        send_resolved: true 
```

prometheus.yaml
```
....
rule_files:
  - rules/*.rules.yml
alerting:
  alert_relabel_configs:
    - target_label: environment
      source_labels: ['env']
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
```

tg.tmpl loaded as usual on docker container starts and telegram plugin installed.
