### ISSUE TITLE
Alerta docker image

### ISSUE THREAD

**Issue by kavyakul** [alerta/prometheus-config#2]
Thanks for building latest image
I am running Prometheus, mongo-db & alerta as docker container & I can see below error:

2016-02-25 07:45:59,381 DEBG 'nginx' stdout output:
2016/02/25 07:45:59 [error] 23#0: *1 open() "/app/webhooks/prometheus" failed (2: No such file or directory), client: 172.17.42.1, server: , request: "POST /webhooks/prometheus HTTP/1.1", host: "<host>:<port>"

client: 172.17.42.1 is the gateway (when I do docker inspect)

Please let me know if I am missing something

**Comment by satterly** [comment]
Thanks for reporting the issue. I'll try to reproduce.

**Comment by satterly** [comment]
When running Alerta in a docker container all the API URLs start with `/api` so your Alertmanager configuration should look something like this (your host/port will be different):

```
receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://192.168.99.100:32768/api/webhooks/prometheus'
    send_resolved: true
```
