### ISSUE TITLE
labels.__name__ not work

### ISSUE THREAD

**Issue by chrishyc** [alerta/prometheus-config#30]
in alertmanager my-rule.yaml
```
groups:
- name: svc-alert-rule
  rules:
  - alert: dubbo_invoke_exception
    expr: "rate({__name__=~'dubbo_.*_fail_.*'}[5m])>0"
    for: 5s
    labels:
      metricsName: '{{ $labels.__name__ }}'
```
{{ $labels.\_\_name\_\_ }} can not get the metric name,
